name: tests
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-24.04-arm
    outputs:
      licenses: ${{ steps.filter.outputs.licenses }}
      format: ${{ steps.filter.outputs.format }}
      lint: ${{ steps.filter.outputs.lint }}
      tests: ${{ steps.filter.outputs.tests }}
      build: ${{ steps.filter.outputs.build }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            licenses:
              - 'package.json'
              - 'package-lock.json'
              - 'ATTRIBUTIONS.md'
              - 'utils/generateLicenseTable.mjs'
              - 'utils/checkLicenses.mjs'
            format:
              - '**/*.ts'
              - '**/*.tsx'
              - '**/*.js'
              - '**/*.jsx'
              - '**/*.mjs'
              - '**/*.cjs'
              - '**/*.json'
              - '**/*.jsonc'
              - '**/*.css'
              - '**/*.scss'
              - '**/*.md'
              - '**/*.yml'
              - '**/*.yaml'
              - '.prettierignore'
              - 'biome.json'
              - 'wxt.config.ts'
              - 'tailwind.config.js'
              - 'postcss.config.js'
              - 'tsconfig.json'
              - 'vitest.config.ts'
              - '.github/**'
            lint:
              - '**/*.ts'
              - '**/*.tsx'
              - '**/*.js'
              - '**/*.jsx'
              - '**/*.mjs'
              - '**/*.cjs'
              - '**/*.json'
              - '**/*.jsonc'
              - 'biome.json'
              - 'wxt.config.ts'
              - 'tailwind.config.js'
              - 'postcss.config.js'
              - 'tsconfig.json'
              - 'vitest.config.ts'
              - '.github/workflows/**/*.yml'
              - 'package.json'
              - 'package-lock.json'
            tests:
              - 'src/**'
              - 'tests/**'
              - 'entrypoints/**'
              - 'assets/**'
              - 'manifest.json'
              - 'messages.ts'
              - 'options.ts'
              - 'rules.json'
              - 'wxt.config.ts'
              - 'tailwind.config.js'
              - 'postcss.config.js'
              - 'tsconfig.json'
              - 'vitest.config.ts'
              - 'package.json'
              - 'package-lock.json'
            build:
              - 'src/**'
              - 'tests/**'
              - 'entrypoints/**'
              - 'assets/**'
              - 'build/**'
              - 'manifest.json'
              - 'messages.ts'
              - 'options.ts'
              - 'rules.json'
              - 'wxt.config.ts'
              - 'tailwind.config.js'
              - 'postcss.config.js'
              - 'tsconfig.json'
              - 'vitest.config.ts'
              - 'package.json'
              - 'package-lock.json'

  format:
    runs-on: ubuntu-24.04-arm
    needs: detect-changes
    if: needs.detect-changes.outputs.format == 'true'
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Prettier formatting
        run: |
          npm run prettier:check || {
            echo "::error::Prettier check failed. Please run `npm run prettier` locally.";
            exit 1;
          }
      - name: Biome formatting
        run: |
          npm run biome:format:check || {
            echo "::error::Biome check failed. Please run `npm run biome:format` locally.";
            exit 1;
          }

  lint:
    runs-on: ubuntu-24.04-arm
    needs: [detect-changes, format]
    if: needs.detect-changes.outputs.lint == 'true'
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Lint
        run: |
          npm run lint:check || {
            echo "::error::Lint check failed. Please run `npm run lint` locally.";
            exit 1;
          }

  unit-tests:
    runs-on: ubuntu-24.04-arm
    needs: detect-changes
    if: needs.detect-changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Run unit tests
        run: npm test

  build-brave:
    runs-on: ubuntu-24.04-arm
    needs: [detect-changes, unit-tests]
    if: needs.detect-changes.outputs.build == 'true'
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Package Brave bundle
        run: |
          npm run package:brave
          ZIP_WITH_VERSION=$(find build -maxdepth 1 -name 'icloud-hide-my-email-plus-browser-extension-*-brave.zip' -print -quit)
          if [ -z "$ZIP_WITH_VERSION" ]; then
            echo "::error::Unable to find Brave package output";
            exit 1;
          fi
          mv "$ZIP_WITH_VERSION" build/icloud-hide-my-email-plus-browser-extension-brave.zip
      - name: Upload Brave artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-browser-extension-brave
          path: build/icloud-hide-my-email-plus-browser-extension-brave.zip

  build-chrome:
    runs-on: ubuntu-24.04-arm
    needs: [detect-changes, unit-tests]
    if: needs.detect-changes.outputs.build == 'true'
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Package Chrome bundle
        run: |
          npm run package:chrome
          ZIP_WITH_VERSION=$(find build -maxdepth 1 -name 'icloud-hide-my-email-plus-browser-extension-*-chrome.zip' -print -quit)
          if [ -z "$ZIP_WITH_VERSION" ]; then
            echo "::error::Unable to find Chrome package output";
            exit 1;
          fi
          mv "$ZIP_WITH_VERSION" build/icloud-hide-my-email-plus-browser-extension-chrome.zip
      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-browser-extension-chrome
          path: build/icloud-hide-my-email-plus-browser-extension-chrome.zip

  build-edge:
    runs-on: ubuntu-24.04-arm
    needs: [detect-changes, unit-tests]
    if: needs.detect-changes.outputs.build == 'true'
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Package Edge bundle
        run: |
          npm run package:edge
          ZIP_WITH_VERSION=$(find build -maxdepth 1 -name 'icloud-hide-my-email-plus-browser-extension-*-edge.zip' -print -quit)
          if [ -z "$ZIP_WITH_VERSION" ]; then
            echo "::error::Unable to find Edge package output";
            exit 1;
          fi
          mv "$ZIP_WITH_VERSION" build/icloud-hide-my-email-plus-browser-extension-edge.zip
      - name: Upload Edge artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-browser-extension-edge
          path: build/icloud-hide-my-email-plus-browser-extension-edge.zip

  build-firefox:
    runs-on: ubuntu-24.04-arm
    needs: [detect-changes, unit-tests]
    if: needs.detect-changes.outputs.build == 'true'
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Package Firefox bundle
        run: |
          npm run package:firefox
          ZIP_WITH_VERSION=$(find build -maxdepth 1 -name 'icloud-hide-my-email-plus-browser-extension-*-firefox.zip' -print -quit)
          if [ -z "$ZIP_WITH_VERSION" ]; then
            echo "::error::Unable to find Firefox package output";
            exit 1;
          fi
          mv "$ZIP_WITH_VERSION" build/icloud-hide-my-email-plus-browser-extension-firefox.zip
      - name: Lint Firefox bundle
        run: npx web-ext lint --source-dir build/firefox-mv3
      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: icloud-hide-my-email-plus-browser-extension-firefox
          path: build/icloud-hide-my-email-plus-browser-extension-firefox.zip

  license-audit:
    needs: detect-changes
    if: needs.detect-changes.outputs.licenses == 'true'
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm deps
        run: npm ci
      - name: Check dependency licenses
        run: npm run check:licenses -- --verbose
